require: datarockets/style

Bundler/DuplicatedGem:
  Enabled: true

Bundler/OrderedGems:
  TreatCommentsAsGroupSeparators: true

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ArrayAlignment:
  Enabled: false

Layout/ArrayAlignmentExtended:
  Description: >-
                 Align the elements of an array literal if they span more than
                 one line.
  EnforcedStyle: with_fixed_indentation
  SupportedStyles:
    - with_first_parameter
    - with_fixed_indentation
  IndentationWidth: ~

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: always_ignore

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/IndentationConsistency:
  EnforcedStyle: normal

Layout/LineLength:
  Max: 120

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NestedInterpolation:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
