require: datarockets/style

Bundler/DuplicatedGem:
  Enabled: true

Bundler/OrderedGems:
  TreatCommentsAsGroupSeparators: true

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ArrayAlignment:
  Enabled: false

Layout/ArrayAlignmentExtended:
  Description: >-
                 Align the elements of an array literal if they span more than
                 one line.
  # Alignment of elements of a multi-line array.
  #
  # The `with_first_parameter` style aligns the following lines along the same
  # column as the first element.
  #
  #     array = [1, 2, 3,
  #              4, 5, 6]
  #
  # The `with_fixed_indentation` style aligns the following lines with one
  # level of indentation relative to the start of the line with start of array.
  #
  #     array = [1, 2, 3,
  #       4, 5, 6]
  EnforcedStyle: with_fixed_indentation
  SupportedStyles:
    - with_first_parameter
    - with_fixed_indentation
  # By default, the indentation width from Layout/IndentationWidth is used
  # But it can be overridden by setting this parameter
  IndentationWidth: ~


Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: always_ignore

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/IndentationConsistency:
  EnforcedStyle: normal

Layout/LineLength:
  Max: 120

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
